doc(mypy): Add type annotations to function defintions
adafruit/Adafruit_CircuitPython_SSD1306 pull request #69
Opened 2021-10-06 03:34 UTC by careyk007

I've taken a stab at #68.

I tried to figure out the correct types and avoid the use of `Any` as much as possible. I can try to dig deeper and remove some of the remaining `Any`s if that would be helpful.

I ran the command `mypy --disallow-untyped-defs --disallow-incomplete-defs --ignore-missing-imports adafruit_ssd1306.py` for verification and received the following output:

```
adafruit_ssd1306.py:269: error: Value of type "Optional[bytearray]" is not indexable
adafruit_ssd1306.py:270: error: Value of type "Optional[bytearray]" is not indexable
adafruit_ssd1306.py:271: error: Unsupported target for indexed assignment ("Optional[bytearray]")
Found 3 errors in 1 file (checked 1 source file)
```

I visually checked these occurrences and they are only indexed if they are not set to `None`, so I think it is acceptable to ignore these errors.

2021-10-07 22:17 UTC, FoamyGuy requested changes
Thanks for working on this @careyk007. I have suggestions on a few of them.

2021-10-07 22:17 UTC, FoamyGuy commented on adafruit_ssd1306.py
> +        i2c: Any,
I think the type for `i2c`  could be `busio.I2C`. It's done similarly with `busio.SPI` here: https://github.com/adafruit/Adafruit_CircuitPython_MAX7219/blob/9e5528117b3a7c20e530ada62c4cbf8d268e7df8/adafruit_max7219/max7219.py#L78

2021-10-07 22:17 UTC, FoamyGuy commented on adafruit_ssd1306.py
> +        spi: Any,
this one can be `busio.SPI` I think.

2021-10-07 22:17 UTC, FoamyGuy commented on adafruit_ssd1306.py
> +        reset: Any,
I think the types for `reset` pins should be `digitalio.DigitalInOut`

2021-10-07 22:17 UTC, FoamyGuy commented on adafruit_ssd1306.py
> +        dc: Any,
`dc` here, and `cs` below are pins so their types can be `digitalio.DigitalInOut`

2021-10-07 23:55 UTC, careyk007 commented
@FoamyGuy Thanks for the review! I added the additional types and some import statements to make the types available.

2021-10-08 00:48 UTC, FoamyGuy approved these changes
Looks good to me. Tested successfully example scripts on:
```
Adafruit CircuitPython 7.0.0 on 2021-09-20; Adafruit Feather RP2040 with rp2040
Board ID:adafruit_feather_rp2040
```

2021-10-10 15:57 UTC, merged